# GitHub Pages configuration

# Site settings
# (Edit these as needed)
title: elsoutlet.github.io
description: Official site for elsoutlet.github.io


# Build settings
# (Uncomment below if you want to use a specific theme)
theme: minima

# Exclude files from the build
exclude:
  - README.md
  - CNAME 